services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab_es
    ports:
      - "8888:8888"
    volumes:
      - ./data:/workspace
      - jupyter_config:/root/.jupyter
    environment:
      TZ: America/Bogota
    restart: unless-stopped

volumes:
  jupyter_config:
